### PR TITLE
Fixed shader to be rendered at the right layer

### PR DESCRIPTION
**Pull request by yuwilbur**

### CODE REVIEW

**Comment by Amarcolina** [comment]
Works for me, but I would recommend using an offset that is larger than 1.  Right now there would be no way to have a shader render after background but before passthrough.  Probably not a big deal but I think it would be good to be safe and place it maybe 50 or so after Background.

**Comment by RandomOutput** [comment]
Currently getting a:

DLLNotFoundException
Leap.Controller.get_PolicyFlags()

which is line 62 of HandController.cs
Controller.PolicyFlag policy_flags = leap_controller_.PolicyFlags;

**Comment by RandomOutput** [comment]
I'm also getting improper passthrough on mac. Just gray flashing quads.

**Comment by RandomOutput** [comment]
Redid the merge and it all looks good. Probably user error.

**Comment by yuwilbur** [comment]
Modified the rendering order from +1 to +50 :)

**Comment by Amarcolina** [comment]
Works great, gonna merge this through

**Pull request merged**
